Openshift login
rht-labs/ansible-stacks pull request #98
Opened 2017-03-02 04:29 UTC by oybed

#### What does this PR do?
Separated out the "openshift-login" role to allow for independent use of this role

#### Which tests illustrate how this code works?
re-run the regression tests to ensure that everything works as it used to

#### Is there a relevant Issue open for this?
N/A

#### Are there any other relevant resources that should be reviewed as well?
N/A

#### Who would you like to review this?
/cc @sherl0cks @mcanoy

2017-03-07 22:45 UTC, sherl0cks requested changes
I'd like the commented code removed if we can

2017-03-07 22:45 UTC, sherl0cks commented on roles/openshift-login/tasks/main.yml
> +#  set_fact:
Why is this commented code here? Can it be removed?

2017-03-07 22:45 UTC, sherl0cks commented on roles/openshift-login/tasks/main.yml
> +  when: auth_token|bool == True
This is an interesting way to keep the token around. I like it.

2017-03-07 22:45 UTC, sherl0cks commented on roles/openshift-login/tasks/main.yml
> +  - oc_login|bool == True
What's the reason behind all the `bool` filters?

2017-03-07 22:52 UTC, oybed commented on roles/openshift-login/tasks/main.yml
> +  - oc_login|bool == True
Due to the many ansible versions we are hitting; casting it to a boolean I've found to be a bit more fail proof across versions

2017-03-07 22:53 UTC, oybed commented on roles/openshift-login/tasks/main.yml
> +  when: auth_token|bool == True
Yes, this is the change Eric made. However, it doesn't work if you don't login (even though the token is valid), hence the extra login step now ...

2017-03-07 22:54 UTC, oybed commented on roles/openshift-login/tasks/main.yml
> +#  set_fact:
oversight ... it should be enabled, but I ran into some issues with it and went an alternative path. I'll re-visit and re-enable.

2017-03-13 15:54 UTC, oybed commented
@sherl0cks commented out code has been fixed and is working. Please re-review and merge if you are ok with the latest.

2017-03-13 18:46 UTC, sherl0cks approved these changes

2017-03-13 18:46 UTC, sherl0cks commented
lgtm

2017-03-13 18:47 UTC, merged